ISSDK: driverexamples/diff_p/diff_p_normal.c File Reference
diff_p_normal.c File Reference
The diff_p_normal.c file implements the ISSDK DIFF_P sensor driver example demonstration with polling mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "diff_p_drv.h"
#include "systick_utils.h"
Macros
#define DIFF_P_DATA_SIZE (3) /* 2 byte Pressure and 1 byte Temperature. */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cDiffPConfigNormal []
Register settings for Normal Mode.
const registerwritelist_t cDiffPClearStatusBits []
Register settings for Clearing Pressure and Temperature Data Ready Bits.
const registerreadlist_t cDiffPStatus [] = {{.readFrom = DIFF_P_INT_STATUS_0, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t cDiffPOutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Detailed Description
The diff_p_normal.c file implements the ISSDK DIFF_P sensor driver example demonstration with polling mode.
Definition in file diff_p_normal.c.
Macro Definition Documentation
DIFF_P_DATA_SIZE
#define DIFF_P_DATA_SIZE (3) /* 2 byte Pressure and 1 byte Temperature. */
Definition at line 35 of file diff_p_normal.c.
Referenced by main().
Function Documentation
main()
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize DIFF_P sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the DIFF_P sensor.
Check for both data ready bits from the DIFF_P.
Read new raw sensor data from the DIFF_P.
Explicitly clear the Status Bits.
Process the sample and convert the raw sensor data.
Definition at line 63 of file diff_p_normal.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), data, diff_p_i2c_sensorhandle_t::deviceInfo, DIFF_P_DATA_SIZE, DIFF_P_I2C_ADDR, DIFF_P_I2C_Configure(), DIFF_P_I2C_Initialize(), DIFF_P_I2C_ReadData(), DIFF_P_I2C_SetIdleTask(), DIFF_P_INT_STATUS_0_PDR_DRDY, DIFF_P_INT_STATUS_0_PDR_MASK, DIFF_P_INT_STATUS_0_TDR_DRDY, DIFF_P_INT_STATUS_0_TDR_MASK, DIFF_P_NPS3000VV_WHOAMI_VALUE, DIFF_P_NPS3001DV_WHOAMI_VALUE, DIFF_P_NPS3002VV_WHOAMI_VALUE, DIFF_P_NPS3005DV_WHOAMI_VALUE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), NPS3000VV_PRESSURE_DIV_FACTOR, NPS3001DV_PRESSURE_DIV_FACTOR, NPS3002VV_PRESSURE_DIV_FACTOR, NPS3005DV_PRESSURE_DIV_FACTOR, diff_p_i2c_sensorhandle_t::pCommDrv, diff_p_pressuredata_t::pressure, rawData, SENSOR_ERROR_NONE, Sensor_I2C_Write(), diff_p_i2c_sensorhandle_t::slaveAddress, SMC, SMC_SetPowerModeVlpr(), status, and diff_p_pressuredata_t::temperature.
Variable Documentation
cDiffPClearStatusBits
const registerwritelist_t cDiffPClearStatusBits[]
Initial value:
= {
    {DIFF_P_INT_STATUS_0, 0x00, DIFF_P_INT_STATUS_0_TDR_MASK | DIFF_P_INT_STATUS_0_PDR_MASK}, __END_WRITE_DATA__}
Register settings for Clearing Pressure and Temperature Data Ready Bits.
Definition at line 47 of file diff_p_normal.c.
cDiffPConfigNormal
const registerwritelist_t cDiffPConfigNormal[]
Initial value:
= {
    {DIFF_P_CTRL_REG2, DIFF_P_CTRL_REG2_ODR_ODR6P25, DIFF_P_CTRL_REG2_ODR_MASK},
    {DIFF_P_CTRL_REG1, DIFF_P_CTRL_REG1_OSR_OSR512, DIFF_P_CTRL_REG1_OSR_MASK},
    __END_WRITE_DATA__}
Register settings for Normal Mode.
Definition at line 41 of file diff_p_normal.c.
cDiffPOutputNormal
const registerreadlist_t cDiffPOutputNormal[]
Initial value:
= {{.readFrom = DIFF_P_OUT_P_LSB, .numBytes = DIFF_P_DATA_SIZE},
                                                 __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 54 of file diff_p_normal.c.
cDiffPStatus
const registerreadlist_t cDiffPStatus[] = {{.readFrom = DIFF_P_INT_STATUS_0, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 51 of file diff_p_normal.c.