ISSDK: boardkit/evk-mimxrt685/clock_config.h File Reference
clock_config.h File Reference
#include "fsl_common.h"
Macros
#define BOARD_SYSOSC_SETTLING_US 260U
#define BOARD_XTAL32K_CLK_HZ 32768U
#define BOARD_XTAL_SYS_CLK_HZ 24000000U
#define BOARD_BOOTCLOCKRUN_CORE_CLOCK 62526315U
Functions
void BOARD_InitBootClocks (void)
This function executes default configuration of clocks.
void BOARD_BootClockRUN (void)
This function executes configuration of clocks.
Macro Definition Documentation
BOARD_BOOTCLOCKRUN_CORE_CLOCK
#define BOARD_BOOTCLOCKRUN_CORE_CLOCK 62526315U
Core clock frequency: 62526315Hz
Definition at line 48 of file clock_config.h.
BOARD_SYSOSC_SETTLING_US
#define BOARD_SYSOSC_SETTLING_US 260U
Board System oscillator settling time in us
Definition at line 20 of file clock_config.h.
Referenced by BOARD_BootClockRUN().
BOARD_XTAL32K_CLK_HZ
#define BOARD_XTAL32K_CLK_HZ 32768U
Board xtal32K frequency in Hz
Definition at line 21 of file clock_config.h.
BOARD_XTAL_SYS_CLK_HZ
#define BOARD_XTAL_SYS_CLK_HZ 24000000U
Board xtal frequency in Hz
Definition at line 22 of file clock_config.h.
Referenced by BOARD_BootClockRUN().
Function Documentation
BOARD_BootClockRUN()
void BOARD_BootClockRUN (void)
This function executes configuration of clocks.
This function executes configuration of clocks.
Parameters
void
Returns
void
Definition at line 168 of file clock_config.c.
References armPllConfig, armPllConfig_BOARD_BootClockRUN, BOARD_BootClockFROHF96M(), BOARD_BOOTCLOCKRUN_CORE_CLOCK, BOARD_SYSOSC_SETTLING_US, BOARD_XTAL0_CLK_HZ, BOARD_XTAL32K_CLK_HZ, BOARD_XTAL_SYS_CLK_HZ, enetPllConfig_BOARD_BootClockRUN, g_enetPllConfig_BOARD_BootClockRUN, g_sysPllConfig_BOARD_BootClockRUN, g_usb1PllConfig_BOARD_BootClockRUN, mcgConfig_BOARD_BootClockRUN, mcgliteConfig_BOARD_BootClockRUN, oscConfig_BOARD_BootClockRUN, simConfig_BOARD_BootClockRUN, sysPllConfig, sysPllConfig_BOARD_BootClockRUN, SystemCoreClock, usb1PllConfig, and usb1PllConfig_BOARD_BootClockRUN.
Referenced by BOARD_InitBootClocks().
BOARD_InitBootClocks()
void BOARD_InitBootClocks (void)
This function executes default configuration of clocks.
Definition at line 52 of file clock_config.c.
References BOARD_BootClockFROHF96M(), and BOARD_BootClockRUN().