ISSDK: algorithms/sensorfusion/sources/main_baremetal_agmp03.c File Reference
main_baremetal_agmp03.c File Reference
Bare metal implementation of sensor fusion on FRDM-K64F.
#include "fsl_debug_console.h"
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_port.h"
#include "fsl_pit.h"
#include "fsl_i2c.h"
#include "fxas21002.h"
#include "fxls8962.h"
#include "mag3110.h"
#include "register_io_i2c.h"
#include "fsl_i2c_cmsis.h"
#include "sensor_fusion.h"
#include "control.h"
#include "status.h"
#include "drivers.h"
#include "driver_pit.h"
Functions
int main (void)
This is a bare-metal implementation of the NXP sensor fusion demo build.
Variables
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
ControlSubsystem controlSubsystem
used for serial communications
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
struct PhysicalSensor sensors [4]
This implementation uses up to 4 sensors.
registerDeviceInfo_t i2cBusInfo
Detailed Description
Bare metal implementation of sensor fusion on FRDM-K64F.
This file shows the recommended way to incorporate sensor fusion capabilities into a bare metal (no RTOS) project.
Definition in file main_baremetal_agmp03.c.
Function Documentation
main()
int main (void)
This is a bare-metal implementation of the NXP sensor fusion demo build.
Definition at line 56 of file main_baremetal_agmp03.c.
References SensorFusionGlobals::applyPerturbation, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), SensorFusionGlobals::conditionSensorReadings, FUSION_HZ, FXAS21002_I2C_ADDR, FXAS21002_Init(), FXAS21002_Read(), FXLS8962_I2C_ADDR, FXLS8962_Init(), FXLS8962_Read(), I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, initializeControlPort(), SensorFusionGlobals::initializeFusionEngine, initializeStatusSubsystem(), initSensorFusionGlobals(), SensorFusionGlobals::installSensor, SensorFusionGlobals::loopcounter, MAG3110_I2C_ADDR, MAG3110_Init(), MAG3110_Read(), MPL3115_I2C_ADDR, MPL3115_Init(), MPL3115_Read(), NORMAL, SensorFusionGlobals::pControlSubsystem, pit_init(), pitIsrFlag, SensorFusionGlobals::queueStatus, SensorFusionGlobals::readSensors, SensorFusionGlobals::runFusion, sensors, SensorFusionGlobals::setStatus, ControlSubsystem::stream, sUARTOutputBuffer, and SensorFusionGlobals::updateStatus.
Variable Documentation
controlSubsystem
ControlSubsystem controlSubsystem
used for serial communications
Definition at line 44 of file main_baremetal_agmp03.c.
i2cBusInfo
registerDeviceInfo_t i2cBusInfo
Initial value:
= {
    .deviceInstance     = I2C_S_DEVICE_INDEX,
    .functionParam      = NULL,
    .idleFunction       = NULL
}
Definition at line 48 of file main_baremetal_agmp03.c.
sensors
struct PhysicalSensor sensors[4]
This implementation uses up to 4 sensors.
Definition at line 46 of file main_baremetal_agmp03.c.
Referenced by main().
sfg
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 43 of file main_baremetal_agmp03.c.
statusSubsystem
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
Definition at line 45 of file main_baremetal_agmp03.c.