ISSDK: driverexamples/mma845x/mma845x_poll.c File Reference
mma845x_poll.c File Reference
The mma845x_poll.c file implements the ISSDK MMA845x sensor driver example demonstration with polling mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "mma845x_drv.h"
Functions
int main (void)
Main function.
Variables
const registerwritelist_t mma845x_Config_Normal []
const registerreadlist_t mma845x_Data_Ready [] = {{.readFrom = MMA845x_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t mma845x_Output_Values []
Detailed Description
The mma845x_poll.c file implements the ISSDK MMA845x sensor driver example demonstration with polling mode.
Definition in file mma845x_poll.c.
Function Documentation
main()
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the MMA845x sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA845x sensor driver with No FIFO mode.
Wait for data ready from the MMA845x.
Read the raw sensor data from the MMA865x.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 58 of file mma845x_poll.c.
References mma845x_acceldata_t::accel, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8451_WHO_AM_I_WHOAMI_VALUE, MMA845x_ACCEL_DATA_SIZE, MMA845x_I2C_ADDR, MMA845x_I2C_Configure(), MMA845x_I2C_Initialize(), MMA845x_I2C_ReadData(), MMA845x_I2C_SetIdleTask(), MMA845x_STATUS_ZYXDR_MASK, rawData, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeVlpr(), and status.
Variable Documentation
mma845x_Config_Normal
const registerwritelist_t mma845x_Config_Normal[]
Initial value:
= {
    {MMA845x_CTRL_REG1, MMA845x_CTRL_REG1_MODE_STANDBY | MMA845x_CTRL_REG1_DR_12DOT5HZ, 0},
    {MMA845x_F_SETUP, MMA845x_F_SETUP_F_MODE_FIFODISABLED, 0},
    {MMA845x_CTRL_REG2, MMA845x_CTRL_REG2_MODS_HIGHRES, 0},
    __END_WRITE_DATA__}
Prepare the register write list to configure MMA845x in poll mode.
Definition at line 36 of file mma845x_poll.c.
mma845x_Data_Ready
const registerreadlist_t mma845x_Data_Ready[] = {{.readFrom = MMA845x_STATUS, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read the Data Ready Status from MMA845x.
Definition at line 46 of file mma845x_poll.c.
mma845x_Output_Values
const registerreadlist_t mma845x_Output_Values[]
Initial value:
= {
    {.readFrom = MMA845x_OUT_X_MSB, .numBytes = MMA845x_ACCEL_DATA_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA845x.
Definition at line 49 of file mma845x_poll.c.