ISSDK: algorithms/pedometer/examples/pedometer_stepcount_mma8451.c File Reference
pedometer_stepcount_mma8451.c File Reference
The pedometer_stepcount_mma8451.c file implements the ISSDK prdometer example using MMA8451 sensor as the acceleration source.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "issdk_hal.h"
#include "pedometer.h"
#include "mma845x_drv.h"
Macros
#define RAW_ACCEL_DATA_SIZE (6)
Functions
int main (void)
Main function.
Variables
const registerwritelist_t mma845x_Config_Normal []
const registerreadlist_t mma845x_Data_Ready [] = {{.readFrom = MMA845x_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t mma845x_Output_Values []
Detailed Description
The pedometer_stepcount_mma8451.c file implements the ISSDK prdometer example using MMA8451 sensor as the acceleration source.
Definition in file pedometer_stepcount_mma8451.c.
Macro Definition Documentation
RAW_ACCEL_DATA_SIZE
#define RAW_ACCEL_DATA_SIZE (6)
Definition at line 32 of file pedometer_stepcount_mma8451.c.
Function Documentation
main()
int main (void)
Main function.
Initialize the MCU hardware
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the MMA845x sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA845x sensor driver with Non FIFO mode.
Initialize the pedometer
Configure the pedometer
Read the data ready status from MMA845x
Read the raw sensor data from the MMA845x.
Convert the raw sensor data for display to the debug port.
Execute the pedometer Algorithm
Definition at line 85 of file pedometer_stepcount_mma8451.c.
References mma845x_acceldata_t::accel, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), data, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8451_WHO_AM_I_WHOAMI_VALUE, MMA845x_ACCEL_DATA_SIZE, MMA845x_I2C_ADDR, MMA845x_I2C_Configure(), MMA845x_I2C_Initialize(), MMA845x_I2C_ReadData(), MMA845x_I2C_SetIdleTask(), MMA845x_STATUS_ZYXDR_MASK, pedometer_configure(), pedometer_init(), pedometer_run(), rawData, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeVlpr(), pedometer_t::status, status, and pedometer_t::pedometer_status_tag::stepcount.
Variable Documentation
mma845x_Config_Normal
const registerwritelist_t mma845x_Config_Normal[]
Initial value:
= {
    {MMA845x_CTRL_REG1, MMA845x_CTRL_REG1_MODE_STANDBY | MMA845x_CTRL_REG1_DR_50HZ, 0},
    {MMA845x_F_SETUP, MMA845x_F_SETUP_F_MODE_FIFODISABLED, 0},
    {MMA845x_CTRL_REG2, MMA845x_CTRL_REG2_SMODS_HIGHRES, 0},
    __END_WRITE_DATA__}
Prepare the register write list to configure MMA845x in poll mode.
Definition at line 39 of file pedometer_stepcount_mma8451.c.
mma845x_Data_Ready
const registerreadlist_t mma845x_Data_Ready[] = {{.readFrom = MMA845x_STATUS, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read the Data Ready Status from MMA845x.
Definition at line 49 of file pedometer_stepcount_mma8451.c.
mma845x_Output_Values
const registerreadlist_t mma845x_Output_Values[]
Initial value:
= {
    {.readFrom = MMA845x_OUT_X_MSB, .numBytes = MMA845x_ACCEL_DATA_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA845x.
Definition at line 52 of file pedometer_stepcount_mma8451.c.