ISSDK: sensors/register_io_spi.c File Reference
register_io_spi.c File Reference
The register_io_spi.c file contains definitions for low-level interface functions for reading and writing sensor registers using CMSIS APIs.
#include <string.h>
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "register_io_spi.h"
Macros
#define SPI_COUNT (sizeof(spiBases) / sizeof(void *))
Functions
void register_spi_control (spiControlParams_t *ssControl)
int32_t Register_SPI_BlockWrite (ARM_DRIVER_SPI *pCommDrv, registerDeviceInfo_t *devInfo, void *pWriteParams, uint8_t offset, const uint8_t *pBuffer, uint8_t bytesToWrite)
The interface function to block write to a sensor register.
int32_t Register_SPI_Write (ARM_DRIVER_SPI *pCommDrv, registerDeviceInfo_t *devInfo, void *pWriteParams, uint8_t offset, uint8_t value, uint8_t mask)
The interface function to write a sensor register.
int32_t Register_SPI_Read (ARM_DRIVER_SPI *pCommDrv, registerDeviceInfo_t *devInfo, void *pReadParams, uint8_t offset, uint8_t length, uint8_t *pOutBuffer)
The interface function to read a sensor register.
Variables
GENERIC_DRIVER_GPIO * pDspiGpioDriver = &Driver_GPIO_KSDK
SPI_Type *const spiBases [] = SPI_BASE_PTRS
volatile bool b_SPI_CompletionFlag [SPI_COUNT] = {false}
volatile uint32_t g_SPI_ErrorEvent [SPI_COUNT] = {ARM_SPI_EVENT_TRANSFER_COMPLETE}
Detailed Description
The register_io_spi.c file contains definitions for low-level interface functions for reading and writing sensor registers using CMSIS APIs.
Definition in file register_io_spi.c.
Macro Definition Documentation
SPI_COUNT
#define SPI_COUNT (sizeof(spiBases) / sizeof(void *))
Definition at line 26 of file register_io_spi.c.
Function Documentation
Register_SPI_BlockWrite()
int32_t Register_SPI_BlockWrite (ARM_DRIVER_SPI * pCommDrv, registerDeviceInfo_t * devInfo, void * pWriteParams, uint8_t offset, const uint8_t * pBuffer, uint8_t bytesToWrite)
The interface function to block write to a sensor register.
The interface function to block write sensor registers.
Write and the value.
Definition at line 149 of file register_io_spi.c.
References b_SPI_CompletionFlag, spiControlParams_t::cmdCode, registerDeviceInfo_t::deviceInstance, registerDeviceInfo_t::functionParam, g_SPI_ErrorEvent, registerDeviceInfo_t::idleFunction, int32_t(), spi_mater_SlaveCmd::pReadBuffer, spiSlaveSpecificParams_t::pTargetSlavePinID, spi_mater_SlaveCmd::pWriteBuffer, spiSlaveSpecificParams_t::pWritePreprocessFN, register_spi_control(), spi_mater_SlaveCmd::size, spiSlaveSpecificParams_t::ssActiveValue, and status.
Referenced by FXLC95000_SPI_Initialize(), Host_IO_Receive(), MMA9553_SPI_Initialize(), and Sensor_SPI_BlockWrite().
register_spi_control()
void register_spi_control (spiControlParams_t * ssControl)
Definition at line 136 of file register_io_spi.c.
References spiControlParams_t::activeValue, GENERIC_DRIVER_GPIO::clr_pin, spiControlParams_t::cmdCode, spiControlParams_t::pTargetSlavePinID, and GENERIC_DRIVER_GPIO::set_pin.
Referenced by Register_SPI_BlockWrite(), Register_SPI_Read(), and Register_SPI_Write().
Register_SPI_Read()
int32_t Register_SPI_Read (ARM_DRIVER_SPI * pCommDrv, registerDeviceInfo_t * devInfo, void * pReadParams, uint8_t offset, uint8_t length, uint8_t * pOutBuffer)
The interface function to read a sensor register.
The interface function to read a sensor register.
Read the value.
Definition at line 300 of file register_io_spi.c.
References b_SPI_CompletionFlag, spiControlParams_t::cmdCode, registerDeviceInfo_t::deviceInstance, registerDeviceInfo_t::functionParam, g_SPI_ErrorEvent, registerDeviceInfo_t::idleFunction, int32_t(), spi_mater_SlaveCmd::pReadBuffer, spiSlaveSpecificParams_t::pReadPreprocessFN, spiSlaveSpecificParams_t::pTargetSlavePinID, spi_mater_SlaveCmd::pWriteBuffer, register_spi_control(), spi_mater_SlaveCmd::size, spiSlaveSpecificParams_t::spiCmdLen, spiSlaveSpecificParams_t::ssActiveValue, and status.
Referenced by ADS_DIFF_PQuery(), ADS_FXLS8471Query(), ADS_FXLS8962Query(), DIFF_P_SPI_Initialize(), FXAS21002_SPI_Initialize(), FXLS8471Q_Init(), FXLS8471Q_SPI_Initialize(), FXLS8962_SPI_Initialize(), FXOS8700_SPI_Initialize(), Host_IO_Receive(), MMA9553_SPI_Configure(), MMA9553_SPI_Initialize(), Sensor_SPI_BlockWrite(), and Sensor_SPI_Read().
Register_SPI_Write()
int32_t Register_SPI_Write (ARM_DRIVER_SPI * pCommDrv, registerDeviceInfo_t * devInfo, void * pWriteParams, uint8_t offset, uint8_t value, uint8_t mask)
The interface function to write a sensor register.
The interface function to write a sensor register.
Set the register based on the values in the register value pair configuration.
Read the register value.
'OR' in the requested values to the current contents of the register
Overwrite the register with specified value.
Write and the value.
Definition at line 203 of file register_io_spi.c.
References b_SPI_CompletionFlag, spiControlParams_t::cmdCode, registerDeviceInfo_t::deviceInstance, registerDeviceInfo_t::functionParam, g_SPI_ErrorEvent, registerDeviceInfo_t::idleFunction, int32_t(), spi_mater_SlaveCmd::pReadBuffer, spiSlaveSpecificParams_t::pReadPreprocessFN, spiSlaveSpecificParams_t::pTargetSlavePinID, spi_mater_SlaveCmd::pWriteBuffer, spiSlaveSpecificParams_t::pWritePreprocessFN, register_spi_control(), spi_mater_SlaveCmd::size, spiSlaveSpecificParams_t::spiCmdLen, spiSlaveSpecificParams_t::ssActiveValue, and status.
Referenced by DIFF_P_SPI_Configure(), DIFF_P_SPI_DeInit(), DIFF_P_SPI_Initialize(), FXAS21002_SPI_Configure(), FXAS21002_SPI_Deinit(), FXLS8471Q_SPI_Configure(), FXLS8962_SPI_Configure(), FXLS8962_SPI_Deinit(), FXOS8700_SPI_Configure(), FXOS8700_SPI_Deinit(), and Sensor_SPI_Write().
Variable Documentation
b_SPI_CompletionFlag
volatile bool b_SPI_CompletionFlag[SPI_COUNT] = {false}
Definition at line 33 of file register_io_spi.c.
Referenced by Register_SPI_BlockWrite(), Register_SPI_Read(), and Register_SPI_Write().
g_SPI_ErrorEvent
volatile uint32_t g_SPI_ErrorEvent[SPI_COUNT] = {ARM_SPI_EVENT_TRANSFER_COMPLETE}
Definition at line 34 of file register_io_spi.c.
Referenced by Register_SPI_BlockWrite(), Register_SPI_Read(), and Register_SPI_Write().
pDspiGpioDriver
GENERIC_DRIVER_GPIO* pDspiGpioDriver = &Driver_GPIO_KSDK
Definition at line 31 of file register_io_spi.c.
spiBases
SPI_Type* const spiBases[] = SPI_BASE_PTRS
Definition at line 32 of file register_io_spi.c.