ISSDK: drivers/systick/systick_utils.h File Reference
systick_utils.h File Reference
ARM Systick Utilities.
Functions
void BOARD_SystickEnable (void)
Function to enable systicks framework.
void BOARD_SystickStart (int32_t *pStart)
Function to Record the Start systick.
int32_t BOARD_SystickElapsedTicks (int32_t *pStart)
Function to compute the Elapsed systicks.
uint32_t BOARD_SystickElapsedTime_us (int32_t *pStart)
Function to compute the Elapsed Time.
void BOARD_DELAY_ms (uint32_t delay_ms)
Function to insert delays.
Detailed Description
ARM Systick Utilities.
This file provides systick based counts for the developer to get cycle counts for measuring time delays.
Definition in file systick_utils.h.
Function Documentation
BOARD_DELAY_ms()
void BOARD_DELAY_ms (uint32_t delay_ms)
Function to insert delays.
This function blocks for the specified milli seconds by using the elapsed systicks to determine time delays.
Parameters
[in] delay_ms The required time to block.
Returns
void.
Constraints:
None. Yes
Definition at line 81 of file systick_utils.c.
References BOARD_SystickElapsedTicks(), BOARD_SystickStart(), and int32_t().
Referenced by ADS_DetectShield(), ADS_MMA9553Query(), DIFF_P_I2C_Initialize(), DIFF_P_SPI_Initialize(), FXLC95000_SPI_Initialize(), FXLS8962_I2C_DeInit(), FXLS8962_SPI_Deinit(), MMA9553_I2C_Initialize(), MMA9553_SPI_Initialize(), Sensor_I2C_BlockWrite(), and Sensor_SPI_BlockWrite().
BOARD_SystickElapsedTicks()
int32_t BOARD_SystickElapsedTicks (int32_t * pStart)
Function to compute the Elapsed systicks.
This function computes the elapsed ticks by getting the difference of the current tick to the one in the arguement.
Parameters
[in] pStart Pointer to the variable contating the start systick.
Returns
int32_t The elapsed systicks.
Constraints:
None. Yes
Definition at line 52 of file systick_utils.c.
References g_ovf_counter, g_ovf_stamp, int32_t(), SYST_CVR, and SYST_RVR.
Referenced by BOARD_DELAY_ms(), and BOARD_SystickElapsedTime_us().
BOARD_SystickElapsedTime_us()
uint32_t BOARD_SystickElapsedTime_us (int32_t * pStart)
Function to compute the Elapsed Time.
This function computes the elapsed Time in micro seconds by getting the difference of the current tick to the one in the arguement. It also updates the start tick to the current systick.
Parameters
[in] pStart Pointer to the variable contating the start systick.
Returns
uint32_t The elapsed Time in micro seconds.
Constraints:
None. Yes
Definition at line 64 of file systick_utils.c.
References BOARD_SystickElapsedTicks(), and BOARD_SystickStart().
Referenced by main().
BOARD_SystickEnable()
void BOARD_SystickEnable (void)
Function to enable systicks framework.
This function initializes the CMSIS define ARM core specific systick implementation.
Parameters
[in] void.
Returns
void.
Constraints:
This should be the first function to be invoked before other Systick APIs. Yes
Definition at line 35 of file systick_utils.c.
References SYST_CSR, and SYST_RVR.
Referenced by main().
BOARD_SystickStart()
void BOARD_SystickStart (int32_t * pStart)
Function to Record the Start systick.
This function records the current systick count for other APIs to compute difference.
Parameters
[in] pStart Pointer to the variable to store the current/start systick.
Returns
void.
Constraints:
None. Yes
Definition at line 44 of file systick_utils.c.
References g_ovf_counter, g_ovf_stamp, and SYST_CVR.
Referenced by BOARD_DELAY_ms(), BOARD_SystickElapsedTime_us(), main(), and process_host_command().