/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MIMX9596xxxxN
package_id: MIMX9596AVZXN
mcu_data: ksdk2_0
processor_version: 16.1.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7}
- pin_list:
  - {pin_num: P44, peripheral: LPUART3, signal: lpuart_rx, pin_signal: GPIO_IO15, SION: DISABLED, PD: ENABLED, FSEL1: SLIGHTLY_FAST_SLEW_RATE}
  - {pin_num: N51, peripheral: LPUART3, signal: lpuart_tx, pin_signal: GPIO_IO14, SION: DISABLED, PD: ENABLED, FSEL1: SLIGHTLY_FAST_SLEW_RATE}
  - {pin_num: V46, peripheral: LPI2C4, signal: lpi2c_sda, pin_signal: GPIO_IO30, SION: ENABLED, OD: ENABLED, PD: DISABLED}
  - {pin_num: V48, peripheral: LPI2C4, signal: lpi2c_scl, pin_signal: GPIO_IO31, SION: ENABLED, OD: ENABLED, PD: DISABLED}
  - {pin_num: P46, peripheral: SAI3, signal: sai_tx_bclk, pin_signal: GPIO_IO16, SION: ENABLED, PD: DISABLED, FSEL1: SlOW_SLEW_RATE}
  - {pin_num: P48, peripheral: SAI3, signal: sai_mclk, pin_signal: GPIO_IO17, SION: ENABLED, PD: DISABLED, FSEL1: SlOW_SLEW_RATE}
  - {pin_num: R49, peripheral: SAI3, signal: 'sai_rx_data_bit, 0', pin_signal: GPIO_IO20, SION: ENABLED, PD: DISABLED, FSEL1: SlOW_SLEW_RATE}
  - {pin_num: R51, peripheral: SAI3, signal: 'sai_tx_data_bit, 0', pin_signal: GPIO_IO21, SION: ENABLED, PD: DISABLED, FSEL1: SlOW_SLEW_RATE}
  - {pin_num: U45, peripheral: SAI3, signal: sai_tx_sync, pin_signal: GPIO_IO26, SION: ENABLED, PD: DISABLED, FSEL1: SlOW_SLEW_RATE}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-M7F[cm7] */
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO14__LPUART3_TX, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO14__LPUART3_TX, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_PD_MASK);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO15__LPUART3_RX, 0U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO15__LPUART3_RX, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_PD_MASK);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO16__SAI3_TX_BCLK, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO16__SAI3_TX_BCLK, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO17__SAI3_MCLK, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO17__SAI3_MCLK, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO20__SAI3_RX_DATA_BIT0, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO20__SAI3_RX_DATA_BIT0, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO21__SAI3_TX_DATA_BIT0, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO21__SAI3_TX_DATA_BIT0, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO26__SAI3_TX_SYNC, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO26__SAI3_TX_SYNC, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U));
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO30__LPI2C4_SDA, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO30__LPI2C4_SDA, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_OD_MASK);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO31__LPI2C4_SCL, 1U);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO31__LPI2C4_SCL, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_OD_MASK);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
