/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DEMO_PANEL LCD_SPEC
#define DPU_EXAMPLE_DI DPU_DI_LVDS
// #define APP_DISPLAY_EXTERNAL_CONVERTOR 0
#define LDB_DUAL_PANEL 0
#define CONFIG_FLASH_BASE_ADDRESS 0x0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
